Don't fail when the Content-Type header is empty
_findMediaDelimiter threw:

> TypeError: flatStr is undefined

because `ContentHandlers.parseResponseContentType` was invoked with an
undefined value in background.js, because `getHeader` returned
`undefined` if the header value was empty.